# Generated by Django 5.2 on 2025-10-18 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('highlight_word', models.CharField(help_text="Слово, яке буде зеленим (наприклад, 'delicious')", max_length=100, verbose_name='Виділене слово')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image_left', models.ImageField(upload_to='about/', verbose_name='Ліве зображення')),
                ('image_right', models.ImageField(upload_to='about/', verbose_name='Праве зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Секція About',
                'verbose_name_plural': 'Секції About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('description', models.TextField(verbose_name='Опис')),
                ('address_image', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='Фото адреси')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва події')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Зображення')),
                ('card_size', models.CharField(choices=[('small', 'Маленька'), ('medium', 'Середня'), ('large', 'Велика')], default='medium', max_length=20, verbose_name='Розмір картки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('icon', models.ImageField(upload_to='features/', verbose_name='Іконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('main', 'Main'), ('we_make', 'We make'), ('products', 'Products'), ('events', 'Events')], max_length=20, verbose_name='Категорія')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Посилання футера',
                'verbose_name_plural': 'Посилання футера',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Підзаголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('hero_image', models.ImageField(upload_to='hero/', verbose_name='Головне зображення')),
                ('premium_users', models.IntegerField(default=0, verbose_name='Premium Users')),
                ('customers', models.IntegerField(default=0, verbose_name='Customers')),
                ('winning', models.IntegerField(default=0, verbose_name='Win/mg')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero секція',
                'verbose_name_plural': 'Hero секції',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва продукту')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name="Об'єм (ml)")),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='StarBucks', max_length=100, verbose_name='Назва сайту')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='Логотип')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
